default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/development.sqlite3

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: <%= ENV['PRODUCTION_DATABASE_NAME'] %>
#   host: <%= ENV['PRODUCTION_DATABASE_HOST'] %>
#   pool: 5
#   username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
#   password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>